[package]
name = "rrt"
version = "0.1.0"
edition = "2021"
authors = ["Jay Mody <jaykmody@gmail.com>"]

[dependencies]
rand = "0.8.3"
rayon = "1.7.0"
indicatif = {version = "0.17.3", features = ["rayon"]}
